# Generated by Django 4.2.1 on 2023-05-05 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 32, 14, 67237, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicacion'),
        ),
    ]
